DROP SEQUENCE POST_SEQ;
CREATE SEQUENCE POST_SEQ NOCACHE;

DROP TABLE POST;
CREATE TABLE POST (
    POST_NO NUMBER NOT NULL,
    WRITER VARCHAR2(30 BYTE) NOT NULL,
    TITLE VARCHAR2(1000 BYTE) NOT NULL,
    CONTENT CLOB,
    IP VARCHAR2(30 BYTE),
    MODIFIED_DATE DATE,
    CREATED_DATE DATE NOT NULL
);

ALTER TABLE POST ADD CONSTRAINT PK_POST PRIMARY KEY(POST_NO);